{% set name = "bayesmbar" %}
{% set version = "0.0.8" %}
{% set python_min = "3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/bayesmbar-{{ version }}.tar.gz
  sha256: ca794f651a1c909dfca881e0acf393f480c34bff3df04623905177ab81289efa

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - jax >=0.6.0
    - jaxlib >=0.6.0
    - blackjax >=1.2.3
    - networkx >=3.3
    - tqdm >=4.66.5
    - pytest >=8.3.2

test:
  imports:
    - bayesmbar
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check

about:
  home: https://github.com/DingGroup/BayesMBAR
  summary: 'Bayesian Multistate Bennett Acceptance Ratio Method'
  description: |
    This repository contains the code for the Bayesian Multistate Bennett Acceptance Ratio Method as described 
    in the paper. BayesMBAR is a Bayesion generalization of the Multistate Bennett Acceptance Ratio (MBAR) 
    method for computing free energy differences between multiple states.

  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://dinglab.io/BayesMBAR/
  dev_url: https://github.com/DingGroup/BayesMBAR

extra:
  recipe-maintainers:
    - xiki-tempula
